// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForwardMessage(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['ForwardMessage'](arg1, arg2, arg3);
}

export function GetFriends() {
  return window['go']['backend']['Backend']['GetFriends']();
}

export function GetGroups() {
  return window['go']['backend']['Backend']['GetGroups']();
}

export function GetMessages(arg1, arg2) {
  return window['go']['backend']['Backend']['GetMessages'](arg1, arg2);
}

export function GetOneBotMessage(arg1) {
  return window['go']['backend']['Backend']['GetOneBotMessage'](arg1);
}

export function GetSelfInfo() {
  return window['go']['backend']['Backend']['GetSelfInfo']();
}

export function GetSessions() {
  return window['go']['backend']['Backend']['GetSessions']();
}

export function MarkChatRead(arg1, arg2) {
  return window['go']['backend']['Backend']['MarkChatRead'](arg1, arg2);
}

export function OpenImage() {
  return window['go']['backend']['Backend']['OpenImage']();
}

export function RecallMessage(arg1) {
  return window['go']['backend']['Backend']['RecallMessage'](arg1);
}

export function SearchMessages(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['SearchMessages'](arg1, arg2, arg3);
}

export function SendImageMessage(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['SendImageMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['SendMessage'](arg1, arg2, arg3);
}

export function SendVoiceMessage(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['SendVoiceMessage'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['backend']['Backend']['SetContext'](arg1);
}

export function Shutdown() {
  return window['go']['backend']['Backend']['Shutdown']();
}

export function StartLagrange() {
  return window['go']['backend']['Backend']['StartLagrange']();
}

export function StartNapCat() {
  return window['go']['backend']['Backend']['StartNapCat']();
}

export function UnreadSummary() {
  return window['go']['backend']['Backend']['UnreadSummary']();
}

export function UploadImage(arg1) {
  return window['go']['backend']['Backend']['UploadImage'](arg1);
}

export function UploadVoice(arg1) {
  return window['go']['backend']['Backend']['UploadVoice'](arg1);
}
