// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {napcat} from '../models';
import {context} from '../models';

export function ForwardMessage(arg1:number,arg2:number,arg3:boolean):Promise<models.Message>;

export function GetFriends():Promise<Array<models.User>>;

export function GetGroupMemberInfo(arg1:number,arg2:number):Promise<napcat.GroupMemberInfo>;

export function GetGroups():Promise<Array<models.Group>>;

export function GetMessages(arg1:number,arg2:boolean,arg3:number):Promise<Array<models.Message>>;

export function GetOneBotMessage(arg1:number):Promise<models.Message>;

export function GetSelfInfo():Promise<Record<string, any>>;

export function GetSessions():Promise<Array<models.ChatSession>>;

export function MarkChatRead(arg1:number,arg2:boolean):Promise<void>;

export function OpenImage():Promise<string>;

export function RecallMessage(arg1:number):Promise<void>;

export function SearchMessages(arg1:string,arg2:number,arg3:boolean):Promise<Array<models.Message>>;

export function SendImageMessage(arg1:number,arg2:boolean,arg3:string):Promise<models.Message>;

export function SendMessage(arg1:number,arg2:boolean,arg3:string):Promise<models.Message>;

export function SendVoiceMessage(arg1:number,arg2:boolean,arg3:string):Promise<models.Message>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function StartLagrange():Promise<void>;

export function StartNapCat():Promise<void>;

export function UnreadSummary():Promise<Array<models.UnreadSummary>>;

export function UploadImage(arg1:string):Promise<string>;

export function UploadVoice(arg1:string):Promise<string>;
